---
data_category: operational
key_path: counts.template_repositories
description: Count of total repo templates used to aggregate all file templates
product_group: source_code
value_type: number
status: active
time_frame: all
data_source: database
tiers:
- premium
- ultimate
performance_indicator_type:
- customer_health_score
- leading_indicator
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
