---
data_category: optional
key_path: usage_activity_by_stage.create.approval_project_rules_with_more_approvers_than_required
description: Number of approval rules with more approvers than required.
product_group: source_code
value_type: number
status: active
time_frame: all
data_source: database
instrumentation_class: ApprovalProjectRulesWithUserMetric
options:
  count_type: more_approvers_than_required
tiers:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
