---
data_category: operational
key_path: usage_activity_by_stage.secure.user_api_fuzzing_jobs
description: Count of API Fuzzing jobs by job name
product_group: dynamic_analysis
value_type: number
status: active
time_frame: all
instrumentation_class: CountUsersCreatingCiBuildsMetric
options:
  secure_type: apifuzzer_fuzz
data_source: database
tiers:
- ultimate
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
