---
data_category: optional
key_path: usage_activity_by_stage.create.total_number_of_locked_files
description: The total number of files which have been locked via the GitLab UI
product_group: source_code
value_type: number
status: active
time_frame: all
data_source: database
tiers:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
