---
data_category: optional
key_path: usage_activity_by_stage.create.merge_requests_with_added_rules
description: Merge requests with added rules
product_group: code_review
product_categories:
- code_review_workflow
value_type: number
status: active
time_frame: all
data_source: database
tiers:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
