---
data_category: optional
key_path: usage_activity_by_stage.release.projects_mirrored_with_pipelines_enabled
description: Count creator_id from projects with repository mirroring enabled.
product_group: pipeline_execution
value_type: number
status: active
time_frame: all
data_source: database
tiers:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
