---
key_path: usage_activity_by_stage.release.environments_approval_required
description: Protected environments that require approval with approval rules
product_group: environments
product_categories:
- continuous_delivery
value_type: number
status: active
milestone: "15.1"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
time_frame: all
data_source: database
data_category: optional
instrumentation_class: CountCiEnvironmentsApprovalRequired
performance_indicator_type: []
tiers:
  - premium
  - ultimate
