---
key_path: counts.count_total_render_duo_pro_lead_page
description: Total count of renders Duo Pro lead page
product_group: acquisition
performance_indicator_type: []
value_type: number
status: active
milestone: '16.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146059
time_frame: all
data_source: internal_events
data_category: optional
tiers:
  - premium
  - ultimate
events:
  - name: render_duo_pro_lead_page
