---
key_path: redis_hll_counters.count_distinct_user_id_from_called_vulnerability_api
description: Count of unique users who called the vulnerability API.
product_group: security_infrastructure
product_categories:
- vulnerability_management
performance_indicator_type: []
value_type: number
status: active
milestone: '17.8'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175762
time_frame:
- 28d
- 7d
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: called_vulnerability_api
  unique: user.id
