---
key_path: counts.count_total_view_tracing_page
description: Total count of users who visited tracing page
product_group: platform_insights
performance_indicator_type: []
value_type: number
status: active
milestone: '17.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/153227
time_frame: all
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: view_tracing_page
