---
key_path: redis_hll_counters.count_distinct_namespace_id_from_applied_license_finding_merge_request_approval_policies
description: Count of unique namespaces where license_finding merge request approval policy was applied
product_group: security_policies
product_categories:
- security_policy_management
performance_indicator_type: []
value_type: number
status: active
milestone: '17.8'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177572
time_frame:
- 28d
- 7d
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: create_approval_rule_from_merge_request_approval_policy
  unique: namespace.id
  filter:
    label: license_finding
