---
key_path: redis_hll_counters.count_distinct_user_id_from_manually_create_vulnerability
description: Count of unique users who manually created a vulnerability.
product_group: security_infrastructure
product_categories:
- vulnerability_management
performance_indicator_type: []
value_type: number
status: active
milestone: '17.9'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/177663
time_frame:
- 28d
- 7d
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: manually_create_vulnerability
  unique: user.id
