---
key_path: redis_hll_counters.count_distinct_namespace_id_from_called_dependency_api
description: Count of unique namespaces where the Dependency API was called
product_group: security_infrastructure
product_categories:
- dependency_management
performance_indicator_type: []
value_type: number
status: active
milestone: '17.8'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/175725
time_frame:
- 28d
- 7d
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: called_dependency_api
  unique: namespace.id
