---
key_path: counts.count_total_trial_registration_success
description: Total count of creations trial successfully
product_group: acquisition
performance_indicator_type: []
value_type: number
status: active
milestone: '17.9'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/179844
time_frame: all
data_source: internal_events
data_category: optional
tiers:
  - ultimate
events:
  - name: trial_registration_success
