---
data_category: optional
key_path: redis_hll_counters.epics_usage.g_project_management_users_removing_epic_emoji_monthly
description: Counts of MAU removing emoji on epic
product_group: product_planning
value_type: number
status: active
milestone: '13.12'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60989
time_frame: 28d
data_source: internal_events
events:
  - name: g_project_management_users_removing_epic_emoji
    unique: user.id
tiers:
- premium
- ultimate
performance_indicator_type: []
