---
data_category: optional
key_path: usage_activity_by_stage_monthly.create.total_number_of_path_locks
description: Number of paths/directories manually locked through the UI
product_group: source_code
value_type: number
status: active
time_frame: 28d
data_source: database
tiers:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
