---
key_path: redis_hll_counters.code_review.i_ee_code_review_merge_request_widget_license_compliance_expand_failed_monthly
description: The count of unique users (monthly) who expanded the License Compliance widget extension in a failed state. Originally wrong event. Fixed in 17.0
product_group: code_review
product_categories:
- code_review_workflow
value_type: number
status: active
milestone: "16.0"
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119918"
time_frame: 28d
data_source: internal_events
data_category: optional
events:
  - name: expand_merge_request_widget
    unique: user.id
    filter:
      label: license_compliance
      property: failed
tiers:
- ultimate
