---
data_category: optional
key_path: redis_hll_counters.epics_usage.epics_usage_total_unique_counts_weekly
description: Total weekly users count for epics_usage
product_group: product_planning
value_type: number
status: active
milestone: '13.11'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56891
time_frame: 7d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
events:
- name: g_project_management_epic_created
  unique: user.id
- name: project_management_users_unchecking_epic_task
  unique: user.id
- name: project_management_users_checking_epic_task
  unique: user.id
- name: g_project_management_users_updating_epic_titles
  unique: user.id
- name: g_project_management_users_updating_epic_descriptions
  unique: user.id
- name: g_project_management_users_creating_epic_notes
  unique: user.id
- name: g_project_management_users_updating_epic_notes
  unique: user.id
- name: g_project_management_users_destroying_epic_notes
  unique: user.id
- name: g_project_management_users_awarding_epic_emoji
  unique: user.id
- name: g_project_management_users_removing_epic_emoji
  unique: user.id
- name: g_project_management_users_setting_epic_start_date_as_fixed
  unique: user.id
- name: g_project_management_users_updating_fixed_epic_start_date
  unique: user.id
- name: g_project_management_users_setting_epic_start_date_as_inherited
  unique: user.id
- name: g_project_management_users_setting_epic_due_date_as_fixed
  unique: user.id
- name: g_project_management_users_updating_fixed_epic_due_date
  unique: user.id
- name: g_project_management_users_setting_epic_due_date_as_inherited
  unique: user.id
- name: g_project_management_epic_issue_added
  unique: user.id
- name: g_project_management_epic_issue_removed
  unique: user.id
- name: g_project_management_epic_issue_moved_from_project
  unique: user.id
- name: g_project_management_users_updating_epic_parent
  unique: user.id
- name: g_project_management_epic_closed
  unique: user.id
- name: g_project_management_epic_reopened
  unique: user.id
- name: g_project_management_issue_promoted_to_epic
  unique: user.id
- name: g_project_management_users_setting_epic_confidential
  unique: user.id
- name: g_project_management_users_setting_epic_visible
  unique: user.id
- name: g_project_management_epic_users_changing_labels
  unique: user.id
- name: g_project_management_epic_destroyed
  unique: user.id
- name: g_project_management_epic_cross_referenced
  unique: user.id
- name: g_project_management_users_epic_issue_added_from_epic
  unique: user.id
- name: g_project_management_epic_related_added
  unique: user.id
- name: g_project_management_epic_related_removed
  unique: user.id
- name: g_project_management_epic_blocking_added
  unique: user.id
- name: g_project_management_epic_blocking_removed
  unique: user.id
- name: g_project_management_epic_blocked_added
  unique: user.id
- name: g_project_management_epic_blocked_removed
  unique: user.id
tiers:
- premium
- ultimate
performance_indicator_type: []
