---
data_category: optional
key_path: redis_hll_counters.ci_secrets_management.i_ci_secrets_management_vault_build_created_weekly
description: Weekly active users creating pipelines that that have the Vault JWT
  with it.
product_group: environments
product_categories:
- secrets_management
value_type: number
status: active
time_frame: 7d
data_source: redis_hll
instrumentation_class: RedisHLLMetric
options:
  events:
  - i_ci_secrets_management_vault_build_created
tiers:
- premium
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
