---
key_path: count_distinct_user_id_from_exclude_anonymised_users_7d
description: Count of distinct users who opted to filter out anonymous users on the analytics dashboard view in the last 7 days.
product_group: platform_insights
performance_indicator_type: []
value_type: number
status: active
milestone: '16.7'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138150
time_frame: 7d
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: exclude_anonymised_users
  unique: user.id
