---
key_path: count_distinct_user_id_from_insights_chart_item_clicked_7d
description: Count of unique users that clicked on any Insights chart item in the last 7 days.
product_group: optimize
performance_indicator_type: []
value_type: number
status: active
milestone: '16.7'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139277
time_frame: 7d
data_source: internal_events
data_category: optional
tiers:
- ultimate
events:
- name: insights_chart_item_clicked
  unique: user.id
