---
data_category: optional
key_path: usage_activity_by_stage_monthly.manage.ldap_group_sync_enabled
description: Has the instance configured [LDAP Group Sync](https://docs.gitlab.com/ee/administration/auth/ldap/#group-sync)
product_group: authentication
value_type: boolean
status: active
time_frame: none
data_source: system
tiers:
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54332
