---
key_path: settings.numbers_password_complexity_required
description: Whether numbers are required for password complexity
product_group: authentication
value_type: boolean
status: active
milestone: "17.5"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/165814
time_frame: none
data_source: database
data_category: optional
instrumentation_class: NumbersPasswordComplexityRequiredMetric
performance_indicator_type: 
- lighthouse
tiers:
- premium
- ultimate
