---
name: compliance_framework_removed
description: A compliance framework is removed from a project
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/464160
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/157893
milestone: '17.2'
feature_category: compliance_management
saved_to_database: true
streamed: true
scope: [Project]
