---
name: group_push_rules_file_name_regex_updated
description: A group's push rules settings is changed for filename regex
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/369344
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/105791
feature_category: source_code_management
milestone: '15.7'
saved_to_database: true
streamed: true
scope: [Group]
