---
name: updated_group_audit_event_streaming_destination
description: An external audit event destination for a top-level group is updated
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/436610
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/148388
feature_category: audit_events
milestone: "16.11"
saved_to_database: true
streamed: true
scope: [Group]
