description: "Close trial status popover"
category: default
action: click_button
extra_properties:
identifiers:
product_group: acquisition
milestone: "14.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66199
tiers:
- premium
- ultimate
additional_properties:
  label:
    description: "`close_popover`"
  property:
    description: "`[forced | voluntary]`"
  value:
    description: "Remaining trial days"
