description: "Copy Maven command"
category: default
action: copy_maven_command
extra_properties:
identifiers:
product_group: package_registry
milestone: "12.6"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/20967
tiers:
- premium
- ultimate
additional_properties:
  label:
    description: "`code_instruction`"
