---
description: The user disables a GitLab Duo seat assignment by clicking on a toggle in the Code Suggestions usage app.
internal_events: true
action: disable_gitlab_duo_pro_for_seat
identifiers:
- namespace
- user
product_group: provision
milestone: '17.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158482
tiers:
- ultimate
