---
description: An epic's due date has been set as inherited
internal_events: true
action: g_project_management_users_setting_epic_due_date_as_inherited
extra_properties:
identifiers:
- user
- namespace
product_group: product_planning
milestone: "16.5"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131896
tiers:
- premium
- ultimate
