---
description: An issue has been removed from an epic
internal_events: true
action: g_project_management_issue_removed_from_epic
extra_properties:
identifiers:
- project
- user
- namespace
product_group: project_management
milestone: "16.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/124431
tiers:
- premium
- ultimate
