---
description: An epic has been set to visible
internal_events: true
action: g_project_management_users_setting_epic_visible
extra_properties:
identifiers:
- project
- user
- namespace
product_group: product_planning
milestone: "16.5"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132027
tiers:
- premium
- ultimate
