---
description: Render Duo Enterprise lead page
internal_events: true
action: render_duo_enterprise_lead_page
identifiers:
  - namespace
  - user
product_group: acquisition
milestone: '16.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/146059
tiers:
  - premium
  - ultimate
