---
description: User viewed the analytics cluster configuration
internal_events: true
action: user_viewed_cluster_configuration
extra_properties:
identifiers:
- project
- user
- namespace
product_group: platform_insights
milestone: "16.4"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131168
tiers:
- ultimate
